version: '3'

services:
  database:
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    healthcheck:
      test: "exit 0"

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy