IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'PushToken')
    BEGIN
        ALTER TABLE Users
            ADD PushToken VARCHAR(100) NULL;
    END
