IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Address' AND COLUMN_NAME = 'Country')
    BEGIN
        ALTER TABLE Address
            ADD Country VARCHAR(50) NOT NULL CONSTRAINT DF_Address_Country DEFAULT 'Poland';
    END
