IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'PushToken')
    BEGIN
        ALTER TABLE Users
            ALTER COLUMN PushToken VARCHAR(255) NULL;
    END
